workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 11
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Set up local properties
        script: mkdir -p android && echo "sdk.dir=$ANDROID_SDK_ROOT" > "./android/local.properties"
      - name: Build Android release
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - vivekvenom138@gmail.com
