workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        # Android Keystore configuration
        CM_KEYSTORE: Encrypted(...) # Add your encrypted keystore here
        CM_KEYSTORE_PASSWORD: Encrypted(...)
        CM_KEY_ALIAS_PASSWORD: Encrypted(...)
        CM_KEY_ALIAS_USERNAME: Encrypted(...)
      node: latest
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI and EAS
        script: |
          npm install -g expo-cli
          npm install -g eas-cli
      - name: Setup app signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
