workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      vars:
        PACKAGE_NAME: "com.vivek1387.coursehub"
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          yarn add expo@latest
          
      - name: Install Expo CLI
        script: |
          yarn add @expo/cli
          yarn expo install
          
      - name: Prepare Android build
        script: |
          # Create a temporary app config that skips image processing
          cat > temp-app.json << EOL
          {
            "expo": {
              "name": "Course Hub",
              "slug": "course-hub-by-vivek",
              "version": "1.0.0",
              "android": {
                "package": "com.vivek1387.coursehub"
              }
            }
          }
          EOL
          
          # Run prebuild with minimal config
          EXPO_CONFIG_PATH=temp-app.json yarn expo prebuild -p android --clean --no-install
          
          # After prebuild, restore original app.json configuration
          cp app.json temp-app.json
      
      - name: Generate debug keystore
        script: |
          cd android
          keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          mv debug.keystore app/
      
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Build Android debug
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
    
    artifacts:
      - android/app/build/outputs/**/*.apk
