workflows:
  expo-production:
    name: Expo Production Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      groups:
        - expo_credentials
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install -g eas-cli@latest
      - name: Setup Expo and EAS
        script: |
          npx expo install
          eas login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - name: Build with EAS
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - '*.apk'
      - '*.aab'
    publishing:
      email:
        recipients:
          - vivekvenom138@gmail.com
      scripts:
        - echo "Build completed successfully!"
