workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Generate Android files
        script: npx expo prebuild -p android --no-install
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "./android/local.properties"
      - name: Make gradlew executable
        script: chmod +x ./android/gradlew
      - name: Set JAVA_HOME
        script: export JAVA_HOME="$JAVA_HOME_17_X64" && echo $JAVA_HOME
      - name: Build Android release
        script: cd android && ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - vivekvenom138@gmail.com
